version: '3.9'
services:
  mysql:
    container_name: hw3_mysql
    hostname: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - hw2_mysql_data:/var/lib/mysql
  nodejs:
    image: keymetrics/pm2:14-alpine
    container_name: hw3_nodejs
    restart: unless-stopped
    env_file: .env
    depends_on:
      - "mysql"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/src
    command: > # This way we don't need a Dockerfile :)
      sh -c "
      cd /src
      && npm install
      && pm2-runtime start pm2.json
      "
volumes:
  hw2_mysql_data: